### ISSUE TITLE
[Bug]: Sync is not working

### ISSUE THREAD

**Issue by jdambacher** [actualbudget/actual#1153]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Sync is not working and it shows red warning sign.

### What error did you receive?

```
2023-06-19T13:10:41.793776655Z PayloadTooLargeError: request entity too large
2023-06-19T13:10:41.793812233Z at readStream (/app/node_modules/raw-body/index.js:156:17)
2023-06-19T13:10:41.793815589Z at getRawBody (/app/node_modules/raw-body/index.js:109:12)
2023-06-19T13:10:41.793818114Z at read (/app/node_modules/body-parser/lib/read.js:79:3)
2023-06-19T13:10:41.793821149Z at rawParser (/app/node_modules/body-parser/lib/types/raw.js:81:5)
2023-06-19T13:10:41.793823644Z at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2023-06-19T13:10:41.793828052Z at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
2023-06-19T13:10:41.793830697Z at /app/node_modules/express/lib/router/index.js:286:9
2023-06-19T13:10:41.793833132Z at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
2023-06-19T13:10:41.793835626Z at next (/app/node_modules/express/lib/router/index.js:280:10)
2023-06-19T13:10:41.793838112Z at jsonParser (/app/node_modules/body-parser/lib/types/json.js:119:7)
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 This is a known issue for large files. Please see here for the recommended solution: https://github.com/actualbudget/actual/issues/867
