### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LonlyGamerX** [actualbudget/actual#1398]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Try syncing data with both a local and a 3rd party account from the web and got an error in my docker container logs

### What error did you receive?

Rejection: SqliteError: no such table: files
    at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at WrappedDatabase.all (file:///app/src/db.js:13:24)
    at file:///app/src/app-sync.js:53:32
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10) {
  code: 'SQLITE_ERROR'
}

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Desktop App (Electron), Other

### Operating System

Linux

**Comment by j-f1** [comment]
It looks like something has corrupted your file `account.sqlite` database. I would recommend exporting the budget file from your browser, then wiping any volumes/mounts you’re using with the Docker container and setting it up again. Once you do that you should be able to import the backed up budget file and continue from where you left off. Does that work?

**Comment by j-f1** [comment]
I’m leaning towards closing this issue for now since you’re the first person I know of who has encountered this particular issue, but if someone else runs into the issue, we should definitely do a deeper search to see if there is a cause on our end.
