### ISSUE TITLE
[Bug]: SqliteError: no such table: auth

### ISSUE THREAD

**Issue by stwalser** [actualbudget/actual#2198]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After a fresh install upon choosing the server I get the message:
_Server does not look like an Actual server. Is it set up correctly?_ in the web interface and the log of my local Docker container shows:

### What error did you receive?

> ERROR SqliteError: no such table: auth
>   at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
>   at WrappedDatabase.all (file:///app/src/db.js:13:24)
>   at needsBootstrap (file:///app/src/account-db.js:24:24)
>   at file:///app/src/app-account.js:25:28
>   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
>   at next (/app/node_modules/express/lib/router/route.js:144:13)
>   at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
>   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
>   at /app/node_modules/express/lib/router/index.js:284:15
>   at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12) {
>   code: 'SQLITE_ERROR'
> }

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Linux

**Comment by purepani** [comment]
@stwalser I've also been getting this error. Did you end up fixing it?

**Comment by stwalser** [comment]
@purepani To be honest I am not sure anymore, but I think I just ended up deleting all files in the docker volumes.
The error occurred to me, when I tried to migrate the data from one device to another. Instead of copying the content of the /data and /config folders, I then exported the data in the GUI and imported it in the new instance.

**Comment by purepani** [comment]
Hmm im getting this even after just deleting everything in the folders

**Comment by RyanHaoo** [comment]
> @stwalser I've also been getting this error. Did you end up fixing it?

Hi I got the same problem during a fresh install today and deleting all data on the server don't fix. Then I cleared all the cache and local storage in the browser and thing are going normally. BTW, I triggered the issue by assign customized `serverFiles` and `userFiles` configuration but forgot to manually set up the path.

Hope this may help!

**Comment by tekumara** [comment]
This was happening for me because I had an empty `server-files/` directory. 

I had to remove it and also `.migrate` to prevent the migrations erroring with:
> TypeError: Cannot open database because the directory does not exist

**Comment by tekumara** [comment]
This happens when the bootstrap fails and is partially complete, so it isn't triggered again.

For me it happened because I had an empty `server-files/` directory. 

I had to remove `server-files/` and also `.migrate` to prevent the migrations erroring with:
> TypeError: Cannot open database because the directory does not exist
