### ISSUE TITLE
[Bug]: RangeError: Maximum call stack size exceeded. when openning the application

### ISSUE THREAD

**Issue by lelemm** [actualbudget/actual#2241]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I just started using Actual. Imported some OFX with no problems, then I imported an CSV, categorized its transactions. Tried to go to budget, this error starts happening. Now I'm unable to open the application at all.

### What error did you receive?

graph-data-structure.ts:79  Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at ep (graph-data-structure.ts:79:13)
    at ep (graph-data-structure.ts:85:9)
    at ep (graph-data-structure.ts:85:9)
    at ep (graph-data-structure.ts:85:9)
    at ep (graph-data-structure.ts:85:9)
    at ep (graph-data-structure.ts:85:9)
    at ep (graph-data-structure.ts:85:9)
    at ep (graph-data-structure.ts:85:9)
    at ep (graph-data-structure.ts:85:9)
    at ep (graph-data-structure.ts:85:9)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by lelemm** [comment]
I was able to isolate the problem.
The CSV that I was importing from the bank had the following date: 1/1/1901
When this transaction is imported, it breaks the application

**Comment by MatissJanis** [comment]
👋 Could you please share an example CSV file so we could reproduce?

Thanks!

**Comment by MatissJanis** [comment]
Closing due to lack of information.

**Comment by lelemm** [comment]
Sorry for the delay.
I imported the CSV like this:
![image](https://github.com/actualbudget/actual/assets/15043428/a461ef43-26d7-4419-99bd-f806293c51f0)

[crash.csv](https://github.com/actualbudget/actual/files/14165218/crash.csv)

Please, do not import this CSV at your production env :)

**Comment by lelemm** [comment]
![image](https://github.com/actualbudget/actual/assets/15043428/617c78e2-4c81-4e21-b3a4-1f796cc5b76c)

example csv that causes the problem:
[https://github.com/actualbudget/actual/files/14165218/crash.csv](url)
