### ISSUE TITLE
[Bug]: API Issues

### ISSUE THREAD

**Issue by lordvault** [actualbudget/actual#2242]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When i try to pull the budget, that generates an error using the API.
I already did a 'Reset sync ' but the error persist.

here the node code, im using:
https://github.com/lordvault/Actual-Budget-Rest-API/blob/development/index.js#L63

tnks for your help. 

### What error did you receive?

`Database is out of sync with migrations: {
  appliedIds: [
    1548957970627, 1550601598648,
    1555786194328, 1561751833510,
    1567699552727, 1582384163573,
    1597756566448, 1608652596043,
    1608652596044, 1612625548236,
    1614782639336, 1615745967948,
    1616167010796, 1618975177358,
    1632571489012, 1679728867040,
    1681115033845, 1682974838138,
    1685007876842, 1686139660866,
    1688749527273, 1688841238000,
    1691233396000, 1694438752000,
    1697046240000
  ],
  available: [
    '1548957970627_remove-db-version.sql',
    '1550601598648_payees.sql',
    '1555786194328_remove_category_group_unique.sql',
    '1561751833510_indexes.sql',
    '1567699552727_budget.sql',
    '1582384163573_cleared.sql',
    '1597756566448_rules.sql',
    '1608652596043_parent_field.sql',
    '1608652596044_trans_views.sql',
    '1612625548236_optimize.sql',
    '1614782639336_trans_views2.sql',
    '1615745967948_meta.sql',
    '1616167010796_accounts_order.sql',
    '1618975177358_schedules.sql',
    '1632571489012_remove_cache.js',
    '1679728867040_rules_conditions.sql',
    '1681115033845_add_schedule_name.sql',
    '1682974838138_remove_payee_rules.sql',
    '1685007876842_add_category_hidden.sql',
    '1686139660866_remove_account_type.sql',
    '1688749527273_transaction_filters.sql',
    '1688841238000_add_account_type.sql',
    '1691233396000_add_schedule_next_date_tombstone.sql'
  ]
}
Error updating Error: out-of-sync-migrations
    at checkDatabaseValidity (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40813:31)
    at Module.migrate (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40821:17)
    at async runMigrations (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44260:17)
    at async updateVersion (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44274:17)
    at async loadBudget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40433:21)
    at async handlers.load-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40274:27)
    at async handlers.download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40244:17)
    at async handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32098:34)
TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43625:96)
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43537:38
    at onceFn (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44451:35)
    at initialFullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43523:36)
    at handlers.sync-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40259:92)
    at handlers.download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40247:55)
    at async handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32098:34)
[Exception] TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43625:96)
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43537:38
    at onceFn (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44451:35)
    at initialFullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43523:36)
    at handlers.sync-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40259:92)
    at handlers.download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40247:55)
    at async handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32098:34)
Full error details {
  message: "Cannot read properties of undefined (reading 'timestamp')",
  reason: undefined,
  meta: undefined
}
2 - Error found: Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
Error: Error downloading budget
    at /usr/src/app/index.js:67:13
    at async addTransaction (/usr/src/app/index.js:63:5)
/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32103
                        throw new Error((0, _shared_errors__WEBPACK_IMPORTED_MODULE_2__.getDownloadError)(result.error));`

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Other

### Operating System

Linux

**Comment by youngcw** [comment]
Is your API version up to date?

**Comment by lordvault** [comment]
> Is your API version up to date?

LOL, tnks for your help hahaha, that was issue. 
Closing this. ...
