### ISSUE TITLE
[Bug]: Creating Schedule from transaction doesn't work

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#2363]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [ ] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [ ] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

When attempting to create a schedule from a transaction nothing happens.  The console shows an error after clicking the "Create new" button.

### What error did you receive?

The console output is always something along these lines
```
ScheduleDetails.jsx:227 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at w (ScheduleDetails.jsx:227:67)
    at ScheduleDetails.jsx:253:5
    at Pg (react-dom.production.min.js:244:332)
    at Ol (react-dom.production.min.js:286:111)
    at QL (react-dom.production.min.js:283:409)
    at Fa (react-dom.production.min.js:281:398)
    at Yk (react-dom.production.min.js:273:439)
    at Ia (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
```

### Where are you hosting Actual?

None

### Operating System

None

**Comment by youngcw** [comment]
@xentara1 Do you have some time to look at this?

**Comment by xentara1** [comment]
Yep will take a look tomorrow :-)On Feb 19, 2024, at 18:21, youngcw ***@***.***> wrote:﻿
@xentara1 Do you have some time to look at this?
