### ISSUE TITLE
[Bug]: Actual very slow (Page Unresponsive)

### ISSUE THREAD

**Issue by lucharo** [actualbudget/actual#2375]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [X] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [X] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

I set up my server yesterday which I am simply running via `yarn start` on a M1 MacBook Pro. I use the latest version of Brave as my browser. Several times already I have had to restart the server for it to function normally and most operations, including search or filter, take a while to complete (> ~10s)

Is any of the hosting alternatives faster? If that is the case I do not believe that was clear from the documentation

### What error did you receive?

![image](https://github.com/actualbudget/actual/assets/47890755/c1984ca1-25df-4dc2-9a1b-9bfbd2ccea98)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Other

### Operating System

Mac OSX

**Comment by lucharo** [comment]
My file is also not "syncing" even though I am doing a local deployment, I have 3 main accounts imported, the largest one with about 8.5k transactions, another one with 1k and the other one with 0.3k, I wouldn't think this is too much but maybe I am doing something wrong. 

```
PayloadTooLargeError: request entity too large
    at readStream (/Users/luischavesrodriguez/Documents/actual-server/node_modules/raw-body/index.js:156:17)
    at getRawBody (/Users/luischavesrodriguez/Documents/actual-server/node_modules/raw-body/index.js:109:12)
    at read (/Users/luischavesrodriguez/Documents/actual-server/node_modules/body-parser/lib/read.js:79:3)
    at rawParser (/Users/luischavesrodriguez/Documents/actual-server/node_modules/body-parser/lib/types/raw.js:81:5)
    at Layer.handle [as handle_request] (/Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/index.js:328:13)
    at /Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/index.js:280:10)
    at rawParser (/Users/luischavesrodriguez/Documents/actual-server/node_modules/body-parser/lib/types/raw.js:76:7)
```

**Comment by youngcw** [comment]
You may need to set the upload size environment variable.  The docker-compose example shows those vars.

**Comment by spktkl** [comment]
> My file is also not "syncing" even though I am doing a local deployment, I have 3 main accounts imported, the largest one with about 8.5k transactions, another one with 1k and the other one with 0.3k, I wouldn't think this is too much but maybe I am doing something wrong.
> 
> ```
> PayloadTooLargeError: request entity too large
>     at readStream (/Users/luischavesrodriguez/Documents/actual-server/node_modules/raw-body/index.js:156:17)
>     at getRawBody (/Users/luischavesrodriguez/Documents/actual-server/node_modules/raw-body/index.js:109:12)
>     at read (/Users/luischavesrodriguez/Documents/actual-server/node_modules/body-parser/lib/read.js:79:3)
>     at rawParser (/Users/luischavesrodriguez/Documents/actual-server/node_modules/body-parser/lib/types/raw.js:81:5)
>     at Layer.handle [as handle_request] (/Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/index.js:328:13)
>     at /Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/index.js:286:9
>     at Function.process_params (/Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/index.js:346:12)
>     at next (/Users/luischavesrodriguez/Documents/actual-server/node_modules/express/lib/router/index.js:280:10)
>     at rawParser (/Users/luischavesrodriguez/Documents/actual-server/node_modules/body-parser/lib/types/raw.js:76:7)
> ```

I had this issue as well, I resolved it by adding a 'config.json' file in the server root directory (actual-server/config.json) with the following:

```
{
    "upload": {
        "fileSizeLimitMB": 50,
        "fileSizeSyncLimitMB": 50,
        "syncEncryptedFileSizeLimitMB": 50
    }
} 
```

This increases the size limit of uploads that the server will accept. The default limits in the code are only set to 100kb for some reason, so it's pretty easy for that error to be triggered.

**Comment by youngcw** [comment]
@lucharo Is this still happening or can I close this issue?

**Comment by lucharo** [comment]
I never hot to the bottom of it, I deleted that budget and created a new one with the same account and all was fine, feel free to close it!
