### ISSUE TITLE
[Bug]: Can't run nYNAB import if 'Income' is a category group

### ISSUE THREAD

**Issue by Marethyu1** [actualbudget/actual#2816]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

If you have a nYNAB budget that has a category group where the name is 'Income' you can't import the budget. 

## Steps to reproduce, 

- import attached example nYnab budget [testbudget.json](https://github.com/user-attachments/files/15520329/testbudget.json)

Error shown in console
```
index.ts:313 Uncaught (in promise) Error: A ’Income’ category group already exists.
    at Module.insertCategoryGroup (index.ts:313:11)
    at async undoDisabled (api.ts:50:24)
```

## Cause
I believe this Is due to Income being a default category group in actual. When it tries to create a category group it fails as a category group already exists https://github.com/actualbudget/actual/blob/08aff05a06f4bca4344f939324080e1fa6511b62/packages/loot-core/src/server/importers/ynab5.ts#L79-L82

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by Marethyu1** [comment]
Discussion about this here https://github.com/actualbudget/actual/issues/1968#issuecomment-2141077903
