### ISSUE TITLE
[Bug]: Desktop Client.  When selecting a tag there is an error

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#2917]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

If a tag is clicked, to filter by that tag, an error message shows.  The filter applies correctly but it seems like the db becomes borked after.  Nothing works after the error comes up.  None of the other pages can load their data.

Ive tested the linux flatpak and appimage.  Both broken.

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Linux

**Comment by youngcw** [comment]
Im guessing this could be fixed by the same potential update that could fix #2917.

**Comment by youngcw** [comment]
fyi, reverting #2763 doesn't fix this issue.

**Comment by youngcw** [comment]
This is the error I get
```error 
    SELECT COUNT('*') AS result FROM v_transactions_internal_alive v_transactions_internal
    LEFT JOIN accounts accounts1 ON accounts1.id = v_transactions_internal.account AND accounts1.tombstone = 0
    WHERE (accounts1.id = '772e97b1-fc3f-4ac7-9d08-7f252acbcfa2'
  AND (REGEXP('(^|\s|\w|#)#153($|\s|#)', UNICODE_LOWER(v_transactions_internal.notes)))) AND v_transactions_internal.is_parent = 0 AND v_transactions_internal.tombstone = 0
    
    ORDER BY v_transactions_internal.date desc, v_transactions_internal.starting_balance_flag, v_transactions_internal.sort_order desc, v_transactions_internal.id
    
    
  
[Exception] SqliteError: no such function: REGEXP
    at Database.prepare (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at nz (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:6:201735)
    at lM (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:135:4969)
    at lk (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:135:5245)
    at i4 (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:62:1545)
    at ar (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:62:3027)
    at Object.transactions (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:94:802)
    at i3 (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:62:1838)
    at i8 (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:62:2066)
    at ao (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:94:948) {
  code: 'SQLITE_ERROR'
}

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
SqliteError: no such function: REGEXP
    at Database.prepare (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at nz (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:6:201735)
    at lM (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:135:4969)
    at lk (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:135:5245)
    at i4 (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:62:1545)
    at ar (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:62:3027)
    at Object.transactions (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:94:802)
    at i3 (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:62:1838)
    at i8 (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:62:2066)
    at ao (/tmp/.mount_Actualkjj7sF/resources/app.asar/node_modules/loot-core/lib-dist/bundle.desktop.js:94:948) {
  code: 'SQLITE_ERROR'
}

Node.js v18.17.1
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
```

**Comment by MikesGlitch** [comment]
Fixed here: https://github.com/actualbudget/actual/pull/2929
