### ISSUE TITLE
[Bug]: PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by natrlhy** [actualbudget/actual#3276]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I've just updated `edge` to last nights build and I am getting the following error when trying to sync or download my budget file I get the following error in the Web App

![Screenshot 2024-08-16 105804](https://github.com/user-attachments/assets/5a759dd3-4dcd-41b8-b85d-8be9c68e2ae2)

My Docker logs also show:

```
actual-server  | PayloadTooLargeError: request entity too large
actual-server  |     at readStream (/app/node_modules/raw-body/index.js:163:17)
actual-server  |     at getRawBody (/app/node_modules/raw-body/index.js:116:12)
actual-server  |     at read (/app/node_modules/body-parser/lib/read.js:79:3)
actual-server  |     at rawParser (/app/node_modules/body-parser/lib/types/raw.js:81:5)
actual-server  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
actual-server  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
actual-server  |     at /app/node_modules/express/lib/router/index.js:286:9
actual-server  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
actual-server  |     at next (/app/node_modules/express/lib/router/index.js:280:10)
actual-server  |     at jsonParser (/app/node_modules/body-parser/lib/types/json.js:122:7)
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by natrlhy** [comment]
I've added these lines to my docker file and it seems to have resolved the Payload error:

```
    environment:
      #- ACTUAL_HTTPS_KEY=/data/selfhost.key
      #- ACTUAL_HTTPS_CERT=/data/selfhost.crt
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=200
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=200
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=200
  ```

But I'm still seeing very slow functionality in the Web App. Clicking on things do nothing, I can't even bank sync or Sync changes to the server. I've tried this on an iPad in Safari as well.

**Comment by natrlhy** [comment]
Adding a console log file...
[console-export-2024-8-16_17-21-47.txt](https://github.com/user-attachments/files/16642847/console-export-2024-8-16_17-21-47.txt)

**Comment by natrlhy** [comment]
Sorry most of the conversation is here:

https://discord.com/channels/937901803608096828/1274057641123119305

**Comment by natrlhy** [comment]
I'm not sure what happened and when but I've deleted the budget file that was causing me issues, restored from a Web App export and it's opening/syncing/closing just fine. Wish I knew what had happened...
