### ISSUE TITLE
Actual is returning a blank page

### ISSUE THREAD

**Issue by felipegrin** [actualbudget/actual#3327]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Hello, I'm running a server through Microsoft Azure and the frontend in netlify. 

Evetything was working fine, but then I renamed my budget file, and then suddenly after I reloaded the page, the front-end (hosted in netlify) is showing a blank page. 

On chrome developer console I have:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'onEventFromMain')
    at WIe (global-events.ts:12:17)
    at index.tsx:68:1
```

I have already tried emptying the cache and redeploying everything, but I still get the blank page with this error in the console. What should I do to get rid of the blank page?

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
What version of actual are you using? Is it the latest `master` or a specific version tag?

Also: does using https://edge.actualbudget.org or https://app.actualbudget.org work for you?

**Comment by MatissJanis** [comment]
Closing due to inactivity
