### ISSUE TITLE
[Bug]: Express 'trust proxy' setting is false (default)

### ISSUE THREAD

**Issue by MarianoRD** [actualbudget/actual#3912]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Actual is not passing the `trust proxy` value to Express and is setup as false.

## Error logs:

```
ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
     at _Validations.<anonymous> (file:///var/www/actual-server/node_modules/express-rate-limit/dist/index.mjs:154:15)
     at _Validations.wrap (file:///var/www/actual-server/node_modules/express-rate-limit/dist/index.mjs:287:18)
     at _Validations.xForwardedForHeader (file:///var/www/actual-server/node_modules/express-rate-limit/dist/index.mjs:152:10)
     at Object.keyGenerator (file:///var/www/actual-server/node_modules/express-rate-limit/dist/index.mjs:516:19)
     at file:///var/www/actual-server/node_modules/express-rate-limit/dist/index.mjs:569:32
     at async file:///var/www/actual-server/node_modules/express-rate-limit/dist/index.mjs:550:5 {
   code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
   help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
 }
```

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Mac OSX

**Comment by MarianoRD** [comment]
Duplicate of https://github.com/actualbudget/actual-server/issues/392
