### ISSUE TITLE
[Bug]: Fatal Error/App Crashes when clicking on Schedules and certain accounts

### ISSUE THREAD

**Issue by ExclamatoryQuestion** [actualbudget/actual#3954]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When I click on the Schedules link in the sidebar or on certain accounts (which, IIRC, are accounts that have schedules linked to them, but I cannot verify), the app crashes. I receive this error:

TypeError: Cannot read properties of null (reading 'num1') at IC (app://actual/static/js/index.rtiWlUvs.js:98:43758) at app://actual/static/js/index.rtiWlUvs.js:98:123249 at Array.map (<anonymous>) at app://actual/static/js/index.rtiWlUvs.js:98:123180 at Object.aM [as useMemo] (app://actual/static/js/index.rtiWlUvs.js:57:23922) at Ye.useMemo (app://actual/static/js/index.rtiWlUvs.js:10:6208) at KBe (app://actual/static/js/index.rtiWlUvs.js:98:123141) at v (app://actual/static/js/useAccountPreviewTransactions.mBtGX4u_.chunk.js:1:117) at Jo (app://actual/static/js/wide.0jCMk_7B.chunk.js:1:89660) at kk (app://actual/static/js/index.rtiWlUvs.js:57:19539)

On Discord, I saw a similar error under the Support thread and the answer was to resave the schedules that had a zero value, but I can't try that because clicking on Schedules causes the app to crash. The app doesn't crash when I click on some of my accounts, but I suspect that is because I don't have any schedules associated with those accounts. My most used accounts do; therefore I can't use Actual to input any transactions. 

I use the Windows app, but encounter the issue when I access my budget using the web via Chrome, Brave, and Firefox. 

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
👋 How can we reproduce the issue?

**Comment by ExclamatoryQuestion** [comment]
I'm not very technical back-end wise; I couldn't post my issue on Github at all without clicking the box that I could replicate the issue. I have no idea what is going on and I'm just trying to see if it is possible to recover my budget or if it is 100% borked. 

I suspect the issue has something to do with schedules but I don't know what because the app crashes as soon as I click the schedules link or (I believe) accounts that have schedules linked.

**Comment by ExclamatoryQuestion** [comment]
This is the discord thread I referenced earlier that seems to have a similar issue. 
https://discord.com/channels/937901803608096828/1309975044608491563

**Comment by matt-fidd** [comment]
Hi! Can you try exporting your budget and importing into https://deploy-preview-3958.demo.actualbudget.org/ please?
All data will stay on your device so no one will be able to see any of your information.

Hopefully you should be able to use the schedules page on there.

**Comment by ExclamatoryQuestion** [comment]
> Hi! Can you try exporting your budget and importing into https://deploy-preview-3958.demo.actualbudget.org/ please? All data will stay on your device so no one will be able to see any of your information.
> 
> Hopefully you should be able to use the schedules page on there.

Thank you! This worked. I was able to resave all my schedules before exporting the new budget file. My budget no longer crashes when I click on schedules or any of my accounts. Thanks again.

**Comment by matt-fidd** [comment]
No problem, glad it worked.

Did you import from YNAB?

**Comment by MatissJanis** [comment]
For what it's worth: I'm currently working on refactoring the schedules component (ScheduleDetails) to TypeScript. And with that - patching various issues that are spotted when the typechecker is added. So that should hopefully resolve the issue for other folks too experiencing this bug 🤞

**Comment by ExclamatoryQuestion** [comment]
> No problem, glad it worked.
> 
> Did you import from YNAB?

Yes, from YNAB4 about 18 months ago or so. But most of the schedules with a zero value were created after I imported.

**Comment by matt-fidd** [comment]
@MatissJanis a Discord user has just provided the steps to reproduce:

> I ask because I ran into this same error after I had deleted the Amount condition on one of the schedules through the Rules table. When I went back to Rules (not Schedules) and added a 0.00 amount condition back, it resolved.

**Comment by ekamil** [comment]
Just had the same issue, I used the preview version to add non-zero amounts and it worked. But I wanted to ask - is this a deliberate choice to require amount on rules?
