### ISSUE TITLE
[Bug]: Error when choosing "imported payee contains" at rule creation

### ISSUE THREAD

**Issue by purrrfecto** [actualbudget/actual#4004]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

My environment:
1. SimpleFIN for bank sync
2. nothing manually imported
3. server self hosted on Home Assistant OS on my Raspbery pi, using [Home Assistant Add-on](https://github.com/sztupy/hassio-actualbudget/blob/795e50d13b511b59246bc944b135e28ac7e45297/README.md) Current version: 24.12.0-alpine 
4. client access from Windows Application from my Windows 10 machine in same local network 
5. stable version

### How can we reproduce the issue?

Side panel > More > Payees > click "Create rule" of any one of the payee 
change condition match from "payee" to "imported payee"
change condition to "contains"

Error would pop up here. seems to mess up the whole system so I need to restart the server

the same error seems not pop up if I go to More > **Rules** and do the same thing. so it only happens from payee?

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 10

**Comment by quarklark** [comment]
Confirming that I'm seeing the same issue on Electron on Mac

**Comment by tekumara** [comment]
Console log shows:
```
Server Log: conditionsToAQL: invalid condition: RuleError: contains must have non-empty string (field: imported_payee)

VM354:2 Server Log: [Exception] TypeError: Cannot read properties of null (reading 'op')
    at gT (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:193:1004)
    at Array.map (<anonymous>)
    at gO (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:193:1504)
    at b5.make-filters-from-conditions (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:294:1147)
    at oY (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:62:2551)
    at ParentPort.<anonymous> (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:62:3194)
    at ParentPort.emit (node:events:518:28)
    at ParentPort.i.emit (node:electron/js2c/utility_init:2:15723)
```

Only happens once when first selecting imported payee contains.

**Comment by tekumara** [comment]
Console log shows:
```
Server Log: conditionsToAQL: invalid condition: RuleError: contains must have non-empty string (field: imported_payee)

VM354:2 Server Log: [Exception] TypeError: Cannot read properties of null (reading 'op')
    at gT (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:193:1004)
    at Array.map (<anonymous>)
    at gO (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:193:1504)
    at b5.make-filters-from-conditions (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:294:1147)
    at oY (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:62:2551)
    at ParentPort.<anonymous> (/Applications/Actual.app/Contents/Resources/app.asar/build/loot-core/lib-dist/electron/bundle.desktop.js:62:3194)
    at ParentPort.emit (node:events:518:28)
    at ParentPort.i.emit (node:electron/js2c/utility_init:2:15723)
```

And then a restart is required to get things back to normal.

**Comment by tekumara** [comment]
A workaround is to first select "imported payee one of", provide a value, and then select "contains". This will ensure the contains value isn't empty, which is what triggers the error.

**Comment by matt-fidd** [comment]
I believe this is fixed now, I can no longer replicate on edge
