### ISSUE TITLE
Bug: able to create Schedule that you cannot view linked transactions for

### ISSUE THREAD

**Issue by zbuc** [actualbudget/actual#581]
Steps to replicate:

1. Create a new schedule
2. Edit the schedule as a rule
3. Remove the amount and/or date constraints from the rule
4. Save the rule/schedule
5. Reopen the schedule
6. Click "Find Matching Transactions"

You'll get an error like the following:

```
react-dom.production.min.js:4928 TypeError: Cannot read properties of undefined (reading 'map')
    at EditSchedule.js:310:31
    at uu (react-dom.production.min.js:5012:1)
    at El (react-dom.production.min.js:6336:1)
    at t.unstable_runWithPriority (scheduler.production.min.js:309:1)
    at Hi (react-dom.production.min.js:2742:1)
    at kl (react-dom.production.min.js:6316:1)
    at react-dom.production.min.js:6305:1
    at U (scheduler.production.min.js:203:1)
    at O.port1.onmessage (scheduler.production.min.js:94:1)
ru @ react-dom.production.min.js:4928
o.componentDidCatch.n.callback @ react-dom.production.min.js:5454
ho @ react-dom.production.min.js:3030
lu @ react-dom.production.min.js:5036
(anonymous) @ react-dom.production.min.js:6253
t.unstable_runWithPriority @ scheduler.production.min.js:309
Hi @ react-dom.production.min.js:2742
_l @ react-dom.production.min.js:6060
sl @ react-dom.production.min.js:5755
(anonymous) @ react-dom.production.min.js:2776
t.unstable_runWithPriority @ scheduler.production.min.js:309
Hi @ react-dom.production.min.js:2742
$i @ react-dom.production.min.js:2772
Yi @ react-dom.production.min.js:2762
El @ react-dom.production.min.js:6349
t.unstable_runWithPriority @ scheduler.production.min.js:309
Hi @ react-dom.production.min.js:2742
kl @ react-dom.production.min.js:6316
(anonymous) @ react-dom.production.min.js:6305
U @ scheduler.production.min.js:203
O.port1.onmessage @ scheduler.production.min.js:94
react-dom.production.min.js:4928 TypeError: Cannot read properties of undefined (reading 'captureException')
    at w.componentDidCatch (App.js:79:27)
    at o.componentDidCatch.n.callback (react-dom.production.min.js:5456:1)
    at ho (react-dom.production.min.js:3030:1)
    at lu (react-dom.production.min.js:5036:1)
    at react-dom.production.min.js:6253:1
    at t.unstable_runWithPriority (scheduler.production.min.js:309:1)
    at Hi (react-dom.production.min.js:2742:1)
    at _l (react-dom.production.min.js:6060:1)
    at sl (react-dom.production.min.js:5755:1)
    at react-dom.production.min.js:2776:1
ru @ react-dom.production.min.js:4928
n.callback @ react-dom.production.min.js:5432
ho @ react-dom.production.min.js:3030
lu @ react-dom.production.min.js:5052
(anonymous) @ react-dom.production.min.js:6253
t.unstable_runWithPriority @ scheduler.production.min.js:309
Hi @ react-dom.production.min.js:2742
_l @ react-dom.production.min.js:6060
sl @ react-dom.production.min.js:5755
(anonymous) @ react-dom.production.min.js:2776
t.unstable_runWithPriority @ scheduler.production.min.js:309
Hi @ react-dom.production.min.js:2742
$i @ react-dom.production.min.js:2772
Yi @ react-dom.production.min.js:2762
El @ react-dom.production.min.js:6349
t.unstable_runWithPriority @ scheduler.production.min.js:309
Hi @ react-dom.production.min.js:2742
kl @ react-dom.production.min.js:6316
(anonymous) @ react-dom.production.min.js:6305
U @ scheduler.production.min.js:203
O.port1.onmessage @ scheduler.production.min.js:94
scheduler.production.min.js:96 Uncaught TypeError: Cannot read properties of undefined (reading 'captureException')
    at w.componentDidCatch (App.js:79:27)
    at o.componentDidCatch.n.callback (react-dom.production.min.js:5456:1)
    at ho (react-dom.production.min.js:3030:1)
    at lu (react-dom.production.min.js:5036:1)
    at react-dom.production.min.js:6253:1
    at t.unstable_runWithPriority (scheduler.production.min.js:309:1)
    at Hi (react-dom.production.min.js:2742:1)
    at _l (react-dom.production.min.js:6060:1)
    at sl (react-dom.production.min.js:5755:1)
    at react-dom.production.min.js:2776:1
    
```

I came across this because I was trying to set up a schedule for a rent payment I receive from a roommate which can vary in date/amount depending on the month. Not sure whether I'm "holding it wrong" or not by trying to do that, but the bug is unexpected.

**Comment by j-f1** [comment]
I suspect this is from:

https://github.com/actualbudget/actual/blob/72006ef64dd410e93a59260af75c23c24f2918c3/packages/desktop-client/src/components/schedules/EditSchedule.js#L300-L310
