### ISSUE TITLE
[Bug]: Cannot sync after large Actual Budget Backup Import (PikaPods)

### ISSUE THREAD

**Issue by pcchristie** [actualbudget/actual#838]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hi Guys,

I am moving from Closed Source to Open (via PikaPods). I have exported from CS. Note I have about 8 years of data - the file is ~ 12MB.

I have imported the file into Open Source via PikaPods. The Sync button top right is red, so I hit sync. It takes a fair while and then produces an error. The logs are attached below.

### What error did you receive?

Here are the logs from PikaPods:

Listening on :::5006...

PayloadTooLargeError: request entity too large

at readStream (/app/node_modules/raw-body/index.js:156:17)

at getRawBody (/app/node_modules/raw-body/index.js:109:12)

at read (/app/node_modules/body-parser/lib/read.js:79:3)

at rawParser (/app/node_modules/body-parser/lib/types/raw.js:81:5)

at Layer.handle s handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)

at /app/node_modules/express/lib/router/index.js:286:9

at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)

at next (/app/node_modules/express/lib/router/index.js:280:10)

at jsonParser (/app/node_modules/body-parser/lib/types/json.js:119:7)

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by pcchristie** [comment]
I have found a solution to this issue. From the Discord:

OK I believe I fixed it. Thanks to @blakegearin for the tip (funny what a search can do). By going back to the Closed Source version and resetting budget cache and resetting sync, my backup (despite being huge years-wise) reduced from 12MB to 2.5MB. This seems to import and sync without any issues. I will note I also had the Pod Resources maxed out to 4 Cores and 12MB RAM, but that didn't seem to be helping before. I recommend anyone else use those two buttons (reset sync and budget cache) before exporting/backing up data!
